---

- name: ensure NFS filesystem for installers is connected
  mount:
    path: /mnt/nfs/installers
    src: "{{ nfs_share }}"
    state: mounted
    fstype: nfs
    opts: auto,nosuid,noatime,nolock,nodev,bg,nfsvers=3,intr,tcp,actimeo=1800
    

...   
