---

- name: ensure packages required for the Enterprise Console are present
  yum:
    name:  "{{ item }}"
    state: latest
    disable_gpg_check: true
  with_items:
    - libaio
    - numactl
    - tzdata
    - ncurses-libs-5*
    - curl

...
