---

- name: ensure Enterprise Console installer is present
  block:
  
  - file:
      path: "{{ shared_installer_directory }}/{{ enterprise_console_script }}"
      state: file
      
  rescue:
  
  - debug:
      msg: Enterprise Console installer is not present, please upload to {{ shared_installer_directory }}
      
  - meta: end_play

...
